import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  Future<void> generateAndPrintReport({
    required Map<String, dynamic> dailySales,
    required Map<String, dynamic> monthlyRevenue,
    required List<dynamic> employeePerformance,
  }) async {
    final pdf = pw.Document();
    final currencyFormat = NumberFormat.currency(symbol: 'INR ', decimalDigits: 0);
    final dateFormat = DateFormat('dd MMM yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            _buildHeader(),
            pw.SizedBox(height: 20),
            _buildDailySalesSection(dailySales, currencyFormat, dateFormat),
            pw.SizedBox(height: 20),
            _buildMonthlyRevenueSection(monthlyRevenue, currencyFormat),
            pw.SizedBox(height: 20),
            _buildEmployeePerformanceSection(employeePerformance, currencyFormat),
            pw.SizedBox(height: 20),
            _buildFooter(),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'RV_Salon_Report_${dateFormat.format(DateTime.now())}',
    );
  }

  pw.Widget _buildHeader() {
    return pw.Header(
      level: 0,
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('RV Salon Manager', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          pw.Text('Report Date: ${DateFormat('dd MMM yyyy').format(DateTime.now())}'),
        ],
      ),
    );
  }

  pw.Widget _buildDailySalesSection(
      Map<String, dynamic> data, NumberFormat currency, DateFormat date) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(border: pw.Border.all()),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Daily Sales (${data['date']})',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Total Sales: ${currency.format(data['totalSales'])}'),
              pw.Text('Total Bills: ${data['totalBills']}'),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildMonthlyRevenueSection(
      Map<String, dynamic> data, NumberFormat currency) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(border: pw.Border.all()),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Monthly Revenue (${data['year']})',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.Text('Total Revenue: ${currency.format(data['totalRevenue'])}'),
          pw.SizedBox(height: 10),
          pw.Table.fromTextArray(
            headers: ['Month', 'Revenue'],
            data: List.generate(12, (index) {
              final monthName = DateFormat('MMM').format(DateTime(2024, index + 1));
              return [monthName, currency.format(data['monthlyRevenue'][index])];
            }),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildEmployeePerformanceSection(
      List<dynamic> data, NumberFormat currency) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(border: pw.Border.all()),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Employee Performance',
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 10),
          pw.Table.fromTextArray(
            headers: ['Name', 'Services', 'Revenue'],
            data: data.map((e) => [
              e['name'],
              e['servicesCount'].toString(),
              currency.format(e['revenue']),
            ]).toList(),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter() {
    return pw.Footer(
      leading: pw.Text('Generated by RV Salon Manager'),
      trailing: pw.Text('Page 1'),
    );
  }
}
